### ISSUE TITLE
Configration format

### ISSUE THREAD

**Issue by Baachi** [DMKEBUSINESSGMBH/dmkhunter#5]
As i started this project i decieded to use the toml format, for the configuration.
Currently the application will looks for an `.hunter.conf` file in the current working directory and reads this. 

The currently configuration format should looks like this:

```toml
[analyzers]
[analyzers.db]
  analzyer = "db"
  paths = ["src/**"]

[reporters]
  [reporters.smtp]
   username = "user"
   password = "user"
   host = "smtp.gmail.com"


```
